export interface College {
  name: string;
  location: string;
  type: string;
  deadlines: {
    "Early Decision": string;
    "Early Action": string;
    "Regular Decision": string;
  };
}

// Deadlines use the most common/typical dates for the 2024-2025 cycle
export const COLLEGES: College[] = [
  { name: "Harvard University", location: "Cambridge, MA", type: "Private Research", deadlines: { "Early Decision": "", "Early Action": "2024-11-01", "Regular Decision": "2025-01-01" } },
  { name: "MIT", location: "Cambridge, MA", type: "Private Research", deadlines: { "Early Decision": "", "Early Action": "2024-11-01", "Regular Decision": "2025-01-01" } },
  { name: "Yale University", location: "New Haven, CT", type: "Private Research", deadlines: { "Early Decision": "2024-11-01", "Early Action": "", "Regular Decision": "2025-01-02" } },
  { name: "Princeton University", location: "Princeton, NJ", type: "Private Research", deadlines: { "Early Decision": "2024-11-01", "Early Action": "", "Regular Decision": "2025-01-01" } },
  { name: "Stanford University", location: "Stanford, CA", type: "Private Research", deadlines: { "Early Decision": "", "Early Action": "2024-11-01", "Regular Decision": "2025-01-02" } },
  { name: "Columbia University", location: "New York, NY", type: "Private Research", deadlines: { "Early Decision": "2024-11-01", "Early Action": "", "Regular Decision": "2025-01-01" } },
  { name: "University of Pennsylvania", location: "Philadelphia, PA", type: "Private Research", deadlines: { "Early Decision": "2024-11-01", "Early Action": "", "Regular Decision": "2025-01-01" } },
  { name: "Brown University", location: "Providence, RI", type: "Private Research", deadlines: { "Early Decision": "2024-11-01", "Early Action": "", "Regular Decision": "2025-01-01" } },
  { name: "Dartmouth College", location: "Hanover, NH", type: "Private Research", deadlines: { "Early Decision": "2024-11-01", "Early Action": "", "Regular Decision": "2025-01-01" } },
  { name: "Cornell University", location: "Ithaca, NY", type: "Private Research", deadlines: { "Early Decision": "2024-11-01", "Early Action": "", "Regular Decision": "2025-01-02" } },
  { name: "Duke University", location: "Durham, NC", type: "Private Research", deadlines: { "Early Decision": "2024-11-01", "Early Action": "", "Regular Decision": "2025-01-02" } },
  { name: "Northwestern University", location: "Evanston, IL", type: "Private Research", deadlines: { "Early Decision": "2024-11-01", "Early Action": "", "Regular Decision": "2025-01-03" } },
  { name: "Vanderbilt University", location: "Nashville, TN", type: "Private Research", deadlines: { "Early Decision": "2024-11-01", "Early Action": "", "Regular Decision": "2025-01-01" } },
  { name: "Rice University", location: "Houston, TX", type: "Private Research", deadlines: { "Early Decision": "2024-11-01", "Early Action": "", "Regular Decision": "2025-01-01" } },
  { name: "Washington University in St. Louis", location: "St. Louis, MO", type: "Private Research", deadlines: { "Early Decision": "2024-11-01", "Early Action": "", "Regular Decision": "2025-01-02" } },
  { name: "Notre Dame University", location: "Notre Dame, IN", type: "Private Research", deadlines: { "Early Decision": "", "Early Action": "2024-11-01", "Regular Decision": "2025-01-01" } },
  { name: "Georgetown University", location: "Washington, DC", type: "Private Research", deadlines: { "Early Decision": "", "Early Action": "2024-11-01", "Regular Decision": "2025-01-10" } },
  { name: "Emory University", location: "Atlanta, GA", type: "Private Research", deadlines: { "Early Decision": "2024-11-01", "Early Action": "", "Regular Decision": "2025-01-15" } },
  { name: "Carnegie Mellon University", location: "Pittsburgh, PA", type: "Private Research", deadlines: { "Early Decision": "2024-11-01", "Early Action": "", "Regular Decision": "2025-01-01" } },
  { name: "Tufts University", location: "Medford, MA", type: "Private Research", deadlines: { "Early Decision": "2024-11-01", "Early Action": "", "Regular Decision": "2025-01-01" } },
  { name: "Tulane University", location: "New Orleans, LA", type: "Private Research", deadlines: { "Early Decision": "2024-11-01", "Early Action": "2024-11-15", "Regular Decision": "2025-01-15" } },
  { name: "Boston College", location: "Chestnut Hill, MA", type: "Private Research", deadlines: { "Early Decision": "2024-11-01", "Early Action": "2024-11-01", "Regular Decision": "2025-01-01" } },
  { name: "Boston University", location: "Boston, MA", type: "Private Research", deadlines: { "Early Decision": "2024-11-01", "Early Action": "", "Regular Decision": "2025-01-02" } },
  { name: "Northeastern University", location: "Boston, MA", type: "Private Research", deadlines: { "Early Decision": "2024-11-01", "Early Action": "2024-11-01", "Regular Decision": "2025-01-01" } },
  { name: "Wake Forest University", location: "Winston-Salem, NC", type: "Private Research", deadlines: { "Early Decision": "2024-11-01", "Early Action": "", "Regular Decision": "2025-01-01" } },
  { name: "Lehigh University", location: "Bethlehem, PA", type: "Private Research", deadlines: { "Early Decision": "2024-11-01", "Early Action": "", "Regular Decision": "2025-01-01" } },
  { name: "Case Western Reserve University", location: "Cleveland, OH", type: "Private Research", deadlines: { "Early Decision": "2024-11-01", "Early Action": "2024-11-15", "Regular Decision": "2025-01-15" } },
  { name: "University of Rochester", location: "Rochester, NY", type: "Private Research", deadlines: { "Early Decision": "2024-11-01", "Early Action": "", "Regular Decision": "2025-01-05" } },
  { name: "Rensselaer Polytechnic Institute", location: "Troy, NY", type: "Private Research", deadlines: { "Early Decision": "2024-11-01", "Early Action": "", "Regular Decision": "2025-01-15" } },
  { name: "Villanova University", location: "Villanova, PA", type: "Private Research", deadlines: { "Early Decision": "2024-11-01", "Early Action": "2024-11-01", "Regular Decision": "2025-02-01" } },
  { name: "Fordham University", location: "New York, NY", type: "Private Research", deadlines: { "Early Decision": "2024-11-01", "Early Action": "2024-11-01", "Regular Decision": "2025-02-01" } },
  // Public Research Universities
  { name: "UCLA", location: "Los Angeles, CA", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2024-11-30" } },
  { name: "UC Berkeley", location: "Berkeley, CA", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2024-11-30" } },
  { name: "UC San Diego", location: "La Jolla, CA", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2024-11-30" } },
  { name: "UC Santa Barbara", location: "Santa Barbara, CA", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2024-11-30" } },
  { name: "UC Davis", location: "Davis, CA", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2024-11-30" } },
  { name: "UC Irvine", location: "Irvine, CA", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2024-11-30" } },
  { name: "UC Santa Cruz", location: "Santa Cruz, CA", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2024-11-30" } },
  { name: "UC Riverside", location: "Riverside, CA", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2024-11-30" } },
  { name: "UC Merced", location: "Merced, CA", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2024-11-30" } },
  { name: "University of Michigan", location: "Ann Arbor, MI", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "2024-11-01", "Regular Decision": "2025-02-01" } },
  { name: "University of Virginia", location: "Charlottesville, VA", type: "Public Research", deadlines: { "Early Decision": "2024-11-01", "Early Action": "", "Regular Decision": "2025-01-01" } },
  { name: "University of North Carolina", location: "Chapel Hill, NC", type: "Public Research", deadlines: { "Early Decision": "2024-10-15", "Early Action": "", "Regular Decision": "2025-01-15" } },
  { name: "Georgia Tech", location: "Atlanta, GA", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "2024-10-15", "Regular Decision": "2025-01-05" } },
  { name: "University of Wisconsin-Madison", location: "Madison, WI", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2024-11-01" } },
  { name: "University of Illinois Urbana-Champaign", location: "Champaign, IL", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2024-11-01" } },
  { name: "Penn State University", location: "University Park, PA", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2024-11-30" } },
  { name: "Ohio State University", location: "Columbus, OH", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "2024-11-01", "Regular Decision": "2025-02-01" } },
  { name: "Purdue University", location: "West Lafayette, IN", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "2024-11-01", "Regular Decision": "2025-02-01" } },
  { name: "University of Florida", location: "Gainesville, FL", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2025-03-01" } },
  { name: "University of Texas at Austin", location: "Austin, TX", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2024-12-01" } },
  { name: "University of Washington", location: "Seattle, WA", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2024-11-15" } },
  { name: "University of Minnesota", location: "Minneapolis, MN", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2024-12-15" } },
  { name: "Michigan State University", location: "East Lansing, MI", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2024-11-01" } },
  { name: "Indiana University Bloomington", location: "Bloomington, IN", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2025-02-01" } },
  { name: "University of Maryland", location: "College Park, MD", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "2024-11-01", "Regular Decision": "2025-01-20" } },
  { name: "Rutgers University", location: "New Brunswick, NJ", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2024-12-01" } },
  { name: "University of Pittsburgh", location: "Pittsburgh, PA", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "2024-11-01", "Regular Decision": "2025-02-15" } },
  { name: "University of Colorado Boulder", location: "Boulder, CO", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2025-01-15" } },
  { name: "University of Arizona", location: "Tucson, AZ", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2025-05-01" } },
  { name: "Arizona State University", location: "Tempe, AZ", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2025-02-01" } },
  { name: "University of Iowa", location: "Iowa City, IA", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2025-04-01" } },
  { name: "University of Oregon", location: "Eugene, OR", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2025-01-15" } },
  { name: "University of Georgia", location: "Athens, GA", type: "Public Research", deadlines: { "Early Decision": "2024-10-15", "Early Action": "2024-10-15", "Regular Decision": "2025-01-01" } },
  { name: "Virginia Tech", location: "Blacksburg, VA", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2025-01-15" } },
  { name: "University of South Carolina", location: "Columbia, SC", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2024-12-01" } },
  { name: "University of Tennessee", location: "Knoxville, TN", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "2024-11-01", "Regular Decision": "2024-12-15" } },
  { name: "University of Alabama", location: "Tuscaloosa, AL", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2025-02-01" } },
  { name: "University of Mississippi", location: "Oxford, MS", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2025-07-01" } },
  { name: "Louisiana State University", location: "Baton Rouge, LA", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2025-04-15" } },
  { name: "University of Nebraska-Lincoln", location: "Lincoln, NE", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2025-05-01" } },
  { name: "Kansas State University", location: "Manhattan, KS", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2025-07-31" } },
  { name: "Iowa State University", location: "Ames, IA", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2025-07-01" } },
  { name: "University of Kentucky", location: "Lexington, KY", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2025-02-15" } },
  { name: "University of Oklahoma", location: "Norman, OK", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2025-04-01" } },
  { name: "Texas A&M University", location: "College Station, TX", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2025-01-15" } },
  { name: "Florida State University", location: "Tallahassee, FL", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "2024-10-15", "Regular Decision": "2025-03-01" } },
  { name: "University of Miami", location: "Coral Gables, FL", type: "Private Research", deadlines: { "Early Decision": "2024-11-01", "Early Action": "2024-11-01", "Regular Decision": "2025-02-01" } },
  { name: "Syracuse University", location: "Syracuse, NY", type: "Private Research", deadlines: { "Early Decision": "2024-11-15", "Early Action": "2024-11-15", "Regular Decision": "2025-01-01" } },
  { name: "University of Connecticut", location: "Storrs, CT", type: "Public Research", deadlines: { "Early Decision": "2024-11-01", "Early Action": "2024-11-01", "Regular Decision": "2025-02-01" } },
  // Liberal Arts Colleges
  { name: "Williams College", location: "Williamstown, MA", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-15", "Early Action": "", "Regular Decision": "2025-01-01" } },
  { name: "Amherst College", location: "Amherst, MA", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-01", "Early Action": "", "Regular Decision": "2025-01-01" } },
  { name: "Swarthmore College", location: "Swarthmore, PA", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-15", "Early Action": "", "Regular Decision": "2025-01-01" } },
  { name: "Pomona College", location: "Claremont, CA", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-15", "Early Action": "", "Regular Decision": "2025-01-08" } },
  { name: "Wellesley College", location: "Wellesley, MA", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-01", "Early Action": "", "Regular Decision": "2025-01-08" } },
  { name: "Bowdoin College", location: "Brunswick, ME", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-15", "Early Action": "", "Regular Decision": "2025-01-05" } },
  { name: "Carleton College", location: "Northfield, MN", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-15", "Early Action": "", "Regular Decision": "2025-01-15" } },
  { name: "Middlebury College", location: "Middlebury, VT", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-01", "Early Action": "", "Regular Decision": "2025-01-01" } },
  { name: "Vassar College", location: "Poughkeepsie, NY", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-15", "Early Action": "", "Regular Decision": "2025-01-01" } },
  { name: "Colby College", location: "Waterville, ME", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-01", "Early Action": "", "Regular Decision": "2025-01-01" } },
  { name: "Colgate University", location: "Hamilton, NY", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-15", "Early Action": "", "Regular Decision": "2025-01-15" } },
  { name: "Hamilton College", location: "Clinton, NY", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-15", "Early Action": "", "Regular Decision": "2025-01-01" } },
  { name: "Wesleyan University", location: "Middletown, CT", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-15", "Early Action": "", "Regular Decision": "2025-01-01" } },
  { name: "Oberlin College", location: "Oberlin, OH", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-15", "Early Action": "", "Regular Decision": "2025-01-15" } },
  { name: "Grinnell College", location: "Grinnell, IA", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-01", "Early Action": "", "Regular Decision": "2025-01-01" } },
  { name: "Smith College", location: "Northampton, MA", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-15", "Early Action": "", "Regular Decision": "2025-01-15" } },
  { name: "Mount Holyoke College", location: "South Hadley, MA", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-15", "Early Action": "", "Regular Decision": "2025-01-15" } },
  { name: "Bryn Mawr College", location: "Bryn Mawr, PA", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-15", "Early Action": "", "Regular Decision": "2025-01-15" } },
  { name: "Bates College", location: "Lewiston, ME", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-15", "Early Action": "", "Regular Decision": "2025-01-01" } },
  { name: "Haverford College", location: "Haverford, PA", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-15", "Early Action": "", "Regular Decision": "2025-01-15" } },
  { name: "Trinity College", location: "Hartford, CT", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-15", "Early Action": "", "Regular Decision": "2025-01-15" } },
  { name: "College of the Holy Cross", location: "Worcester, MA", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-15", "Early Action": "2024-11-15", "Regular Decision": "2025-01-15" } },
  // Additional notable schools
  { name: "Caltech", location: "Pasadena, CA", type: "Private Research", deadlines: { "Early Decision": "", "Early Action": "2024-11-01", "Regular Decision": "2025-01-03" } },
  { name: "Johns Hopkins University", location: "Baltimore, MD", type: "Private Research", deadlines: { "Early Decision": "2024-11-01", "Early Action": "", "Regular Decision": "2025-01-02" } },
  { name: "University of Chicago", location: "Chicago, IL", type: "Private Research", deadlines: { "Early Decision": "2024-11-01", "Early Action": "", "Regular Decision": "2025-01-02" } },
  { name: "New York University", location: "New York, NY", type: "Private Research", deadlines: { "Early Decision": "2024-11-01", "Early Action": "", "Regular Decision": "2025-01-01" } },
  { name: "Babson College", location: "Babson Park, MA", type: "Private", deadlines: { "Early Decision": "2024-11-01", "Early Action": "2024-11-01", "Regular Decision": "2025-02-01" } },
  { name: "Bentley University", location: "Waltham, MA", type: "Private", deadlines: { "Early Decision": "2024-11-15", "Early Action": "2024-11-15", "Regular Decision": "2025-02-01" } },
  { name: "College of William & Mary", location: "Williamsburg, VA", type: "Public Research", deadlines: { "Early Decision": "2024-11-01", "Early Action": "2024-11-01", "Regular Decision": "2025-01-08" } },
  { name: "James Madison University", location: "Harrisonburg, VA", type: "Public", deadlines: { "Early Decision": "", "Early Action": "2024-11-01", "Regular Decision": "2025-01-15" } },
  { name: "Gonzaga University", location: "Spokane, WA", type: "Private", deadlines: { "Early Decision": "2024-11-15", "Early Action": "2024-11-15", "Regular Decision": "2025-02-01" } },
  { name: "Santa Clara University", location: "Santa Clara, CA", type: "Private", deadlines: { "Early Decision": "2024-11-01", "Early Action": "2024-11-01", "Regular Decision": "2025-01-15" } },
  { name: "Loyola Marymount University", location: "Los Angeles, CA", type: "Private", deadlines: { "Early Decision": "2024-11-01", "Early Action": "2024-11-15", "Regular Decision": "2025-01-15" } },
  { name: "Pepperdine University", location: "Malibu, CA", type: "Private", deadlines: { "Early Decision": "2024-11-01", "Early Action": "2024-11-01", "Regular Decision": "2025-01-15" } },
  { name: "Chapman University", location: "Orange, CA", type: "Private", deadlines: { "Early Decision": "2024-11-01", "Early Action": "2024-11-01", "Regular Decision": "2025-01-15" } },
  { name: "University of San Diego", location: "San Diego, CA", type: "Private", deadlines: { "Early Decision": "2024-11-01", "Early Action": "2024-11-15", "Regular Decision": "2025-02-15" } },
  { name: "University of Denver", location: "Denver, CO", type: "Private Research", deadlines: { "Early Decision": "2024-11-01", "Early Action": "2024-11-01", "Regular Decision": "2025-01-15" } },
  { name: "American University", location: "Washington, DC", type: "Private Research", deadlines: { "Early Decision": "2024-11-15", "Early Action": "2024-11-15", "Regular Decision": "2025-01-15" } },
  { name: "George Washington University", location: "Washington, DC", type: "Private Research", deadlines: { "Early Decision": "2024-11-01", "Early Action": "2024-11-01", "Regular Decision": "2025-01-05" } },
  { name: "Howard University", location: "Washington, DC", type: "Private Research", deadlines: { "Early Decision": "2024-11-01", "Early Action": "2024-11-01", "Regular Decision": "2025-02-15" } },
  { name: "Spelman College", location: "Atlanta, GA", type: "Private Liberal Arts", deadlines: { "Early Decision": "2024-11-01", "Early Action": "2024-11-01", "Regular Decision": "2025-02-01" } },
  { name: "Morehouse College", location: "Atlanta, GA", type: "Private Liberal Arts", deadlines: { "Early Decision": "2024-11-01", "Early Action": "2024-11-01", "Regular Decision": "2025-02-15" } },
  { name: "Xavier University of Louisiana", location: "New Orleans, LA", type: "Private", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2025-03-01" } },
  { name: "Drexel University", location: "Philadelphia, PA", type: "Private Research", deadlines: { "Early Decision": "2024-11-01", "Early Action": "2024-11-01", "Regular Decision": "2025-03-01" } },
  { name: "Temple University", location: "Philadelphia, PA", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "2024-11-01", "Regular Decision": "2025-03-01" } },
  { name: "Stony Brook University", location: "Stony Brook, NY", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2025-01-15" } },
  { name: "CUNY Baruch College", location: "New York, NY", type: "Public", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2025-02-01" } },
  { name: "Hunter College (CUNY)", location: "New York, NY", type: "Public", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2025-03-15" } },
  { name: "Rochester Institute of Technology", location: "Rochester, NY", type: "Private", deadlines: { "Early Decision": "2024-12-01", "Early Action": "2024-12-01", "Regular Decision": "2025-03-01" } },
  { name: "Worcester Polytechnic Institute", location: "Worcester, MA", type: "Private", deadlines: { "Early Decision": "2024-11-01", "Early Action": "2024-11-01", "Regular Decision": "2025-02-01" } },
  { name: "Stevens Institute of Technology", location: "Hoboken, NJ", type: "Private", deadlines: { "Early Decision": "2024-11-15", "Early Action": "2024-11-15", "Regular Decision": "2025-02-01" } },
  { name: "Bucknell University", location: "Lewisburg, PA", type: "Private", deadlines: { "Early Decision": "2024-11-15", "Early Action": "", "Regular Decision": "2025-01-15" } },
  { name: "Dickinson College", location: "Carlisle, PA", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-15", "Early Action": "", "Regular Decision": "2025-02-01" } },
  { name: "Franklin & Marshall College", location: "Lancaster, PA", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-15", "Early Action": "", "Regular Decision": "2025-02-01" } },
  { name: "Gettysburg College", location: "Gettysburg, PA", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-15", "Early Action": "", "Regular Decision": "2025-02-01" } },
  { name: "Muhlenberg College", location: "Allentown, PA", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-15", "Early Action": "", "Regular Decision": "2025-02-15" } },
  { name: "Lafayette College", location: "Easton, PA", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-15", "Early Action": "", "Regular Decision": "2025-01-15" } },
  { name: "Union College", location: "Schenectady, NY", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-15", "Early Action": "", "Regular Decision": "2025-01-15" } },
  { name: "Skidmore College", location: "Saratoga Springs, NY", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-15", "Early Action": "", "Regular Decision": "2025-01-15" } },
  { name: "Hobart and William Smith Colleges", location: "Geneva, NY", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-15", "Early Action": "", "Regular Decision": "2025-02-01" } },
  { name: "St. Lawrence University", location: "Canton, NY", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-01", "Early Action": "2024-11-15", "Regular Decision": "2025-02-01" } },
  { name: "Macalester College", location: "St. Paul, MN", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-01", "Early Action": "", "Regular Decision": "2025-01-15" } },
  { name: "Lawrence University", location: "Appleton, WI", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-01", "Early Action": "", "Regular Decision": "2025-01-15" } },
  { name: "Kenyon College", location: "Gambier, OH", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-15", "Early Action": "", "Regular Decision": "2025-01-15" } },
  { name: "Denison University", location: "Granville, OH", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-15", "Early Action": "", "Regular Decision": "2025-01-15" } },
  { name: "College of Wooster", location: "Wooster, OH", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-15", "Early Action": "", "Regular Decision": "2025-02-15" } },
  { name: "DePauw University", location: "Greencastle, IN", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-01", "Early Action": "2024-12-01", "Regular Decision": "2025-03-01" } },
  { name: "Wabash College", location: "Crawfordsville, IN", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-15", "Early Action": "", "Regular Decision": "2025-03-15" } },
  { name: "Rhodes College", location: "Memphis, TN", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-01", "Early Action": "2024-11-15", "Regular Decision": "2025-01-15" } },
  { name: "Davidson College", location: "Davidson, NC", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-15", "Early Action": "", "Regular Decision": "2025-01-10" } },
  { name: "Furman University", location: "Greenville, SC", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-01", "Early Action": "2024-12-01", "Regular Decision": "2025-01-15" } },
  { name: "Sewanee: The University of the South", location: "Sewanee, TN", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-15", "Early Action": "2024-12-01", "Regular Decision": "2025-02-01" } },
  { name: "Centre College", location: "Danville, KY", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-15", "Early Action": "", "Regular Decision": "2025-02-01" } },
  { name: "Hendrix College", location: "Conway, AR", type: "Liberal Arts", deadlines: { "Early Decision": "", "Early Action": "2024-11-15", "Regular Decision": "2025-05-01" } },
  { name: "Reed College", location: "Portland, OR", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-01", "Early Action": "", "Regular Decision": "2025-01-15" } },
  { name: "Whitman College", location: "Walla Walla, WA", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-15", "Early Action": "", "Regular Decision": "2025-01-15" } },
  { name: "Lewis & Clark College", location: "Portland, OR", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-01", "Early Action": "2024-11-01", "Regular Decision": "2025-01-15" } },
  { name: "Willamette University", location: "Salem, OR", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-01", "Early Action": "2024-11-15", "Regular Decision": "2025-03-01" } },
  { name: "University of Redlands", location: "Redlands, CA", type: "Private", deadlines: { "Early Decision": "2024-11-15", "Early Action": "2024-11-15", "Regular Decision": "2025-03-01" } },
  { name: "Claremont McKenna College", location: "Claremont, CA", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-01", "Early Action": "", "Regular Decision": "2025-01-08" } },
  { name: "Harvey Mudd College", location: "Claremont, CA", type: "Private", deadlines: { "Early Decision": "2024-11-01", "Early Action": "", "Regular Decision": "2025-01-03" } },
  { name: "Scripps College", location: "Claremont, CA", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-01", "Early Action": "", "Regular Decision": "2025-01-08" } },
  { name: "Pitzer College", location: "Claremont, CA", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-15", "Early Action": "", "Regular Decision": "2025-01-01" } },
  { name: "Occidental College", location: "Los Angeles, CA", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-15", "Early Action": "", "Regular Decision": "2025-01-10" } },
  { name: "University of Puget Sound", location: "Tacoma, WA", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-15", "Early Action": "2024-12-01", "Regular Decision": "2025-02-01" } },
  { name: "Colorado College", location: "Colorado Springs, CO", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-01", "Early Action": "", "Regular Decision": "2025-01-15" } },
  { name: "University of Tulsa", location: "Tulsa, OK", type: "Private", deadlines: { "Early Decision": "2024-11-01", "Early Action": "2024-11-01", "Regular Decision": "2025-08-01" } },
  { name: "Beloit College", location: "Beloit, WI", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-01", "Early Action": "2024-12-01", "Regular Decision": "2025-02-01" } },
  { name: "Knox College", location: "Galesburg, IL", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-01", "Early Action": "2024-12-01", "Regular Decision": "2025-02-01" } },
  { name: "Illinois Wesleyan University", location: "Bloomington, IL", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-15", "Early Action": "2024-12-01", "Regular Decision": "2025-03-01" } },
  { name: "Augustana College", location: "Rock Island, IL", type: "Liberal Arts", deadlines: { "Early Decision": "2024-11-15", "Early Action": "2024-12-01", "Regular Decision": "2025-05-01" } },
  { name: "Creighton University", location: "Omaha, NE", type: "Private", deadlines: { "Early Decision": "", "Early Action": "2024-11-01", "Regular Decision": "2025-02-15" } },
  { name: "Marquette University", location: "Milwaukee, WI", type: "Private", deadlines: { "Early Decision": "", "Early Action": "2024-12-01", "Regular Decision": "2025-02-01" } },
  { name: "Xavier University", location: "Cincinnati, OH", type: "Private", deadlines: { "Early Decision": "2024-11-15", "Early Action": "2024-11-15", "Regular Decision": "2025-02-01" } },
  { name: "Seton Hall University", location: "South Orange, NJ", type: "Private", deadlines: { "Early Decision": "2024-11-15", "Early Action": "2024-12-01", "Regular Decision": "2025-03-01" } },
  { name: "Providence College", location: "Providence, RI", type: "Private", deadlines: { "Early Decision": "2024-11-01", "Early Action": "2024-11-15", "Regular Decision": "2025-01-15" } },
  { name: "Stonehill College", location: "Easton, MA", type: "Private", deadlines: { "Early Decision": "2024-11-15", "Early Action": "2024-11-15", "Regular Decision": "2025-02-01" } },
  { name: "Fairfield University", location: "Fairfield, CT", type: "Private", deadlines: { "Early Decision": "2024-11-15", "Early Action": "2024-11-15", "Regular Decision": "2025-01-15" } },
  { name: "Quinnipiac University", location: "Hamden, CT", type: "Private", deadlines: { "Early Decision": "2024-11-01", "Early Action": "2024-11-15", "Regular Decision": "2025-02-01" } },
  { name: "Sacred Heart University", location: "Fairfield, CT", type: "Private", deadlines: { "Early Decision": "", "Early Action": "2025-01-01", "Regular Decision": "2025-04-01" } },
  { name: "Ithaca College", location: "Ithaca, NY", type: "Private", deadlines: { "Early Decision": "2024-11-01", "Early Action": "", "Regular Decision": "2025-02-01" } },
  { name: "Marist College", location: "Poughkeepsie, NY", type: "Private", deadlines: { "Early Decision": "2024-11-15", "Early Action": "2024-11-15", "Regular Decision": "2025-02-15" } },
  { name: "Manhattan College", location: "Riverdale, NY", type: "Private", deadlines: { "Early Decision": "2024-11-15", "Early Action": "2024-12-01", "Regular Decision": "2025-03-01" } },
  { name: "Long Island University", location: "Brookville, NY", type: "Private", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2025-08-15" } },
  { name: "Pace University", location: "New York, NY", type: "Private", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2025-08-01" } },
  { name: "University at Buffalo", location: "Buffalo, NY", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2025-02-01" } },
  { name: "University at Albany", location: "Albany, NY", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2025-04-01" } },
  { name: "Binghamton University", location: "Binghamton, NY", type: "Public Research", deadlines: { "Early Decision": "", "Early Action": "2024-11-15", "Regular Decision": "2025-01-15" } },
  { name: "New Paltz (SUNY)", location: "New Paltz, NY", type: "Public", deadlines: { "Early Decision": "", "Early Action": "", "Regular Decision": "2025-03-15" } },
];