export interface School {
  id: string;
  name: string;
  location: string;
  type: "public" | "private";
  deadlines: {
    earlyDecision?: string;
    earlyAction?: string;
    regularDecision: string;
    financialAid?: string;
  };
  website: string;
  logo?: string;
}

export const SCHOOLS: School[] = [
  {
    id: "harvard",
    name: "Harvard University",
    location: "Cambridge, MA",
    type: "private",
    deadlines: {
      earlyAction: "2024-11-01",
      regularDecision: "2025-01-01",
      financialAid: "2025-02-01",
    },
    website: "https://college.harvard.edu",
  },
  {
    id: "yale",
    name: "Yale University",
    location: "New Haven, CT",
    type: "private",
    deadlines: {
      earlyAction: "2024-11-01",
      regularDecision: "2025-01-02",
      financialAid: "2025-03-01",
    },
    website: "https://admissions.yale.edu",
  },
  {
    id: "mit",
    name: "MIT",
    location: "Cambridge, MA",
    type: "private",
    deadlines: {
      earlyAction: "2024-11-01",
      regularDecision: "2025-01-01",
      financialAid: "2025-02-15",
    },
    website: "https://admissions.mit.edu",
  },
  {
    id: "stanford",
    name: "Stanford University",
    location: "Stanford, CA",
    type: "private",
    deadlines: {
      earlyAction: "2024-11-01",
      regularDecision: "2025-01-02",
      financialAid: "2025-02-15",
    },
    website: "https://admission.stanford.edu",
  },
  {
    id: "caltech",
    name: "Caltech",
    location: "Pasadena, CA",
    type: "private",
    deadlines: {
      earlyAction: "2024-11-01",
      regularDecision: "2025-01-03",
      financialAid: "2025-03-01",
    },
    website: "https://admissions.caltech.edu",
  },
  {
    id: "princeton",
    name: "Princeton University",
    location: "Princeton, NJ",
    type: "private",
    deadlines: {
      earlyAction: "2024-11-01",
      regularDecision: "2025-01-01",
      financialAid: "2025-02-01",
    },
    website: "https://admission.princeton.edu",
  },
  {
    id: "columbia",
    name: "Columbia University",
    location: "New York, NY",
    type: "private",
    deadlines: {
      earlyDecision: "2024-11-01",
      regularDecision: "2025-01-01",
      financialAid: "2025-03-01",
    },
    website: "https://undergrad.admissions.columbia.edu",
  },
  {
    id: "upenn",
    name: "University of Pennsylvania",
    location: "Philadelphia, PA",
    type: "private",
    deadlines: {
      earlyDecision: "2024-11-01",
      regularDecision: "2025-01-05",
      financialAid: "2025-02-15",
    },
    website: "https://admissions.upenn.edu",
  },
  {
    id: "brown",
    name: "Brown University",
    location: "Providence, RI",
    type: "private",
    deadlines: {
      earlyDecision: "2024-11-01",
      regularDecision: "2025-01-05",
      financialAid: "2025-03-01",
    },
    website: "https://admission.brown.edu",
  },
  {
    id: "dartmouth",
    name: "Dartmouth College",
    location: "Hanover, NH",
    type: "private",
    deadlines: {
      earlyDecision: "2024-11-01",
      regularDecision: "2025-01-02",
      financialAid: "2025-02-01",
    },
    website: "https://admissions.dartmouth.edu",
  },
  {
    id: "cornell",
    name: "Cornell University",
    location: "Ithaca, NY",
    type: "private",
    deadlines: {
      earlyDecision: "2024-11-01",
      regularDecision: "2025-01-02",
      financialAid: "2025-02-15",
    },
    website: "https://admissions.cornell.edu",
  },
  {
    id: "duke",
    name: "Duke University",
    location: "Durham, NC",
    type: "private",
    deadlines: {
      earlyDecision: "2024-11-01",
      regularDecision: "2025-01-02",
      financialAid: "2025-03-15",
    },
    website: "https://admissions.duke.edu",
  },
  {
    id: "uchicago",
    name: "University of Chicago",
    location: "Chicago, IL",
    type: "private",
    deadlines: {
      earlyAction: "2024-11-01",
      regularDecision: "2025-01-02",
      financialAid: "2025-02-15",
    },
    website: "https://collegeadmissions.uchicago.edu",
  },
  {
    id: "vanderbilt",
    name: "Vanderbilt University",
    location: "Nashville, TN",
    type: "private",
    deadlines: {
      earlyDecision: "2024-11-01",
      regularDecision: "2025-01-01",
      financialAid: "2025-02-15",
    },
    website: "https://admissions.vanderbilt.edu",
  },
  {
    id: "rice",
    name: "Rice University",
    location: "Houston, TX",
    type: "private",
    deadlines: {
      earlyDecision: "2024-11-01",
      regularDecision: "2025-01-04",
      financialAid: "2025-03-01",
    },
    website: "https://admission.rice.edu",
  },
  {
    id: "notre-dame",
    name: "University of Notre Dame",
    location: "Notre Dame, IN",
    type: "private",
    deadlines: {
      earlyAction: "2024-11-01",
      regularDecision: "2025-01-01",
      financialAid: "2025-02-15",
    },
    website: "https://admissions.nd.edu",
  },
  {
    id: "georgetown",
    name: "Georgetown University",
    location: "Washington, DC",
    type: "private",
    deadlines: {
      earlyAction: "2024-11-01",
      regularDecision: "2025-01-10",
      financialAid: "2025-02-01",
    },
    website: "https://uadmissions.georgetown.edu",
  },
  {
    id: "emory",
    name: "Emory University",
    location: "Atlanta, GA",
    type: "private",
    deadlines: {
      earlyDecision: "2024-11-01",
      regularDecision: "2025-01-01",
      financialAid: "2025-03-01",
    },
    website: "https://apply.emory.edu",
  },
  {
    id: "northwestern",
    name: "Northwestern University",
    location: "Evanston, IL",
    type: "private",
    deadlines: {
      earlyDecision: "2024-11-01",
      regularDecision: "2025-01-02",
      financialAid: "2025-02-15",
    },
    website: "https://admissions.northwestern.edu",
  },
  {
    id: "tufts",
    name: "Tufts University",
    location: "Medford, MA",
    type: "private",
    deadlines: {
      earlyDecision: "2024-11-01",
      regularDecision: "2025-01-01",
      financialAid: "2025-02-15",
    },
    website: "https://admissions.tufts.edu",
  },
  {
    id: "washu",
    name: "Washington University in St. Louis",
    location: "St. Louis, MO",
    type: "private",
    deadlines: {
      earlyDecision: "2024-11-01",
      regularDecision: "2025-01-02",
      financialAid: "2025-02-01",
    },
    website: "https://admissions.wustl.edu",
  },
  {
    id: "johns-hopkins",
    name: "Johns Hopkins University",
    location: "Baltimore, MD",
    type: "private",
    deadlines: {
      earlyDecision: "2024-11-01",
      regularDecision: "2025-01-02",
      financialAid: "2025-03-01",
    },
    website: "https://apply.jhu.edu",
  },
  {
    id: "carnegie-mellon",
    name: "Carnegie Mellon University",
    location: "Pittsburgh, PA",
    type: "private",
    deadlines: {
      earlyDecision: "2024-11-01",
      regularDecision: "2025-01-01",
      financialAid: "2025-02-15",
    },
    website: "https://admission.cmu.edu",
  },
  {
    id: "georgetown",
    name: "Georgetown University",
    location: "Washington, DC",
    type: "private",
    deadlines: {
      earlyAction: "2024-11-01",
      regularDecision: "2025-01-10",
      financialAid: "2025-02-01",
    },
    website: "https://uadmissions.georgetown.edu",
  },
  {
    id: "uc-berkeley",
    name: "UC Berkeley",
    location: "Berkeley, CA",
    type: "public",
    deadlines: {
      regularDecision: "2024-11-30",
      financialAid: "2025-03-02",
    },
    website: "https://admissions.berkeley.edu",
  },
  {
    id: "ucla",
    name: "UCLA",
    location: "Los Angeles, CA",
    type: "public",
    deadlines: {
      regularDecision: "2024-11-30",
      financialAid: "2025-03-02",
    },
    website: "https://admissions.ucla.edu",
  },
  {
    id: "ucsb",
    name: "UC Santa Barbara",
    location: "Santa Barbara, CA",
    type: "public",
    deadlines: {
      regularDecision: "2024-11-30",
      financialAid: "2025-03-02",
    },
    website: "https://admissions.ucsb.edu",
  },
  {
    id: "ucsd",
    name: "UC San Diego",
    location: "La Jolla, CA",
    type: "public",
    deadlines: {
      regularDecision: "2024-11-30",
      financialAid: "2025-03-02",
    },
    website: "https://admissions.ucsd.edu",
  },
  {
    id: "ucdavis",
    name: "UC Davis",
    location: "Davis, CA",
    type: "public",
    deadlines: {
      regularDecision: "2024-11-30",
      financialAid: "2025-03-02",
    },
    website: "https://admissions.ucdavis.edu",
  },
  {
    id: "michigan",
    name: "University of Michigan",
    location: "Ann Arbor, MI",
    type: "public",
    deadlines: {
      earlyAction: "2024-11-01",
      regularDecision: "2025-02-01",
      financialAid: "2025-02-15",
    },
    website: "https://admissions.umich.edu",
  },
  {
    id: "virginia",
    name: "University of Virginia",
    location: "Charlottesville, VA",
    type: "public",
    deadlines: {
      earlyDecision: "2024-11-01",
      regularDecision: "2025-01-01",
      financialAid: "2025-03-01",
    },
    website: "https://admission.virginia.edu",
  },
  {
    id: "unc",
    name: "UNC Chapel Hill",
    location: "Chapel Hill, NC",
    type: "public",
    deadlines: {
      earlyAction: "2024-10-15",
      regularDecision: "2025-01-15",
      financialAid: "2025-03-01",
    },
    website: "https://admissions.unc.edu",
  },
  {
    id: "georgia-tech",
    name: "Georgia Tech",
    location: "Atlanta, GA",
    type: "public",
    deadlines: {
      earlyAction: "2024-10-15",
      regularDecision: "2025-01-04",
      financialAid: "2025-02-15",
    },
    website: "https://admission.gatech.edu",
  },
  {
    id: "ut-austin",
    name: "University of Texas at Austin",
    location: "Austin, TX",
    type: "public",
    deadlines: {
      earlyAction: "2024-11-01",
      regularDecision: "2024-12-01",
      financialAid: "2025-03-15",
    },
    website: "https://admissions.utexas.edu",
  },
  {
    id: "ohio-state",
    name: "Ohio State University",
    location: "Columbus, OH",
    type: "public",
    deadlines: {
      earlyAction: "2024-11-01",
      regularDecision: "2025-02-01",
      financialAid: "2025-02-15",
    },
    website: "https://undergrad.osu.edu",
  },
  {
    id: "penn-state",
    name: "Penn State University",
    location: "University Park, PA",
    type: "public",
    deadlines: {
      regularDecision: "2024-11-30",
      financialAid: "2025-02-15",
    },
    website: "https://admissions.psu.edu",
  },
  {
    id: "purdue",
    name: "Purdue University",
    location: "West Lafayette, IN",
    type: "public",
    deadlines: {
      earlyAction: "2024-11-01",
      regularDecision: "2025-02-01",
      financialAid: "2025-03-01",
    },
    website: "https://admissions.purdue.edu",
  },
  {
    id: "boston-college",
    name: "Boston College",
    location: "Chestnut Hill, MA",
    type: "private",
    deadlines: {
      earlyDecision: "2024-11-01",
      regularDecision: "2025-01-01",
      financialAid: "2025-02-01",
    },
    website: "https://www.bc.edu/admission",
  },
  {
    id: "bu",
    name: "Boston University",
    location: "Boston, MA",
    type: "private",
    deadlines: {
      earlyDecision: "2024-11-01",
      regularDecision: "2025-01-02",
      financialAid: "2025-02-15",
    },
    website: "https://www.bu.edu/admissions",
  },
  {
    id: "nyu",
    name: "New York University",
    location: "New York, NY",
    type: "private",
    deadlines: {
      earlyDecision: "2024-11-01",
      regularDecision: "2025-01-05",
      financialAid: "2025-02-15",
    },
    website: "https://www.nyu.edu/admissions",
  },
  {
    id: "usc",
    name: "University of Southern California",
    location: "Los Angeles, CA",
    type: "private",
    deadlines: {
      earlyAction: "2024-11-01",
      regularDecision: "2025-01-15",
      financialAid: "2025-02-15",
    },
    website: "https://admission.usc.edu",
  },
  {
    id: "wake-forest",
    name: "Wake Forest University",
    location: "Winston-Salem, NC",
    type: "private",
    deadlines: {
      earlyDecision: "2024-11-15",
      regularDecision: "2025-01-01",
      financialAid: "2025-03-01",
    },
    website: "https://admissions.wfu.edu",
  },
  {
    id: "tulane",
    name: "Tulane University",
    location: "New Orleans, LA",
    type: "private",
    deadlines: {
      earlyAction: "2024-11-01",
      regularDecision: "2025-01-15",
      financialAid: "2025-02-15",
    },
    website: "https://tulane.edu/admission",
  },
  {
    id: "lehigh",
    name: "Lehigh University",
    location: "Bethlehem, PA",
    type: "private",
    deadlines: {
      earlyDecision: "2024-11-01",
      regularDecision: "2025-01-01",
      financialAid: "2025-02-15",
    },
    website: "https://admissions.lehigh.edu",
  },
  {
    id: "brandeis",
    name: "Brandeis University",
    location: "Waltham, MA",
    type: "private",
    deadlines: {
      earlyDecision: "2024-11-01",
      regularDecision: "2025-01-01",
      financialAid: "2025-02-01",
    },
    website: "https://www.brandeis.edu/admissions",
  },
  {
    id: "rpi",
    name: "Rensselaer Polytechnic Institute",
    location: "Troy, NY",
    type: "private",
    deadlines: {
      earlyDecision: "2024-11-01",
      regularDecision: "2025-01-15",
      financialAid: "2025-02-01",
    },
    website: "https://admissions.rpi.edu",
  },
  {
    id: "case-western",
    name: "Case Western Reserve University",
    location: "Cleveland, OH",
    type: "private",
    deadlines: {
      earlyDecision: "2024-11-01",
      regularDecision: "2025-01-15",
      financialAid: "2025-02-01",
    },
    website: "https://admission.case.edu",
  },
  {
    id: "rochester",
    name: "University of Rochester",
    location: "Rochester, NY",
    type: "private",
    deadlines: {
      earlyDecision: "2024-11-01",
      regularDecision: "2025-01-05",
      financialAid: "2025-02-01",
    },
    website: "https://enrollment.rochester.edu",
  },
  {
    id: "villanova",
    name: "Villanova University",
    location: "Villanova, PA",
    type: "private",
    deadlines: {
      earlyAction: "2024-11-01",
      regularDecision: "2025-01-15",
      financialAid: "2025-02-07",
    },
    website: "https://www1.villanova.edu/admissions",
  },
  {
    id: "fordham",
    name: "Fordham University",
    location: "New York, NY",
    type: "private",
    deadlines: {
      earlyAction: "2024-11-01",
      regularDecision: "2025-01-15",
      financialAid: "2025-02-01",
    },
    website: "https://www.fordham.edu/admission",
  },
];