export interface School {
  id: string;
  name: string;
  location: string;
  state: string;
  type: "public" | "private";
  commonAppDeadline?: string; // MM-DD format (typical, not year-specific)
  earlyActionDeadline?: string;
  earlyDecisionDeadline?: string;
  regularDecisionDeadline?: string;
  website: string;
  acceptanceRate?: number; // percentage
}

export const SCHOOLS: School[] = [
  // Ivy League
  {
    id: "harvard",
    name: "Harvard University",
    location: "Cambridge, MA",
    state: "MA",
    type: "private",
    earlyActionDeadline: "11-01",
    regularDecisionDeadline: "01-01",
    website: "https://college.harvard.edu",
    acceptanceRate: 3.4,
  },
  {
    id: "yale",
    name: "Yale University",
    location: "New Haven, CT",
    state: "CT",
    type: "private",
    earlyActionDeadline: "11-01",
    regularDecisionDeadline: "01-02",
    website: "https://admissions.yale.edu",
    acceptanceRate: 4.6,
  },
  {
    id: "princeton",
    name: "Princeton University",
    location: "Princeton, NJ",
    state: "NJ",
    type: "private",
    earlyActionDeadline: "11-01",
    regularDecisionDeadline: "01-01",
    website: "https://admission.princeton.edu",
    acceptanceRate: 4.7,
  },
  {
    id: "columbia",
    name: "Columbia University",
    location: "New York, NY",
    state: "NY",
    type: "private",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "01-01",
    website: "https://undergrad.admissions.columbia.edu",
    acceptanceRate: 3.9,
  },
  {
    id: "upenn",
    name: "University of Pennsylvania",
    location: "Philadelphia, PA",
    state: "PA",
    type: "private",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "01-05",
    website: "https://admissions.upenn.edu",
    acceptanceRate: 5.9,
  },
  {
    id: "brown",
    name: "Brown University",
    location: "Providence, RI",
    state: "RI",
    type: "private",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "01-05",
    website: "https://admission.brown.edu",
    acceptanceRate: 5.1,
  },
  {
    id: "dartmouth",
    name: "Dartmouth College",
    location: "Hanover, NH",
    state: "NH",
    type: "private",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "01-03",
    website: "https://admissions.dartmouth.edu",
    acceptanceRate: 6.2,
  },
  {
    id: "cornell",
    name: "Cornell University",
    location: "Ithaca, NY",
    state: "NY",
    type: "private",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "01-02",
    website: "https://admissions.cornell.edu",
    acceptanceRate: 7.3,
  },
  // Top Tech / STEM
  {
    id: "stanford",
    name: "Stanford University",
    location: "Stanford, CA",
    state: "CA",
    type: "private",
    earlyActionDeadline: "11-01",
    regularDecisionDeadline: "01-02",
    website: "https://admission.stanford.edu",
    acceptanceRate: 3.7,
  },
  {
    id: "mit",
    name: "Massachusetts Institute of Technology",
    location: "Cambridge, MA",
    state: "MA",
    type: "private",
    earlyActionDeadline: "11-01",
    regularDecisionDeadline: "01-01",
    website: "https://mitadmissions.org",
    acceptanceRate: 3.9,
  },
  {
    id: "caltech",
    name: "California Institute of Technology",
    location: "Pasadena, CA",
    state: "CA",
    type: "private",
    earlyActionDeadline: "11-01",
    regularDecisionDeadline: "01-03",
    website: "https://admissions.caltech.edu",
    acceptanceRate: 2.9,
  },
  {
    id: "cmu",
    name: "Carnegie Mellon University",
    location: "Pittsburgh, PA",
    state: "PA",
    type: "private",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "01-03",
    website: "https://admission.cmu.edu",
    acceptanceRate: 11.0,
  },
  {
    id: "georgia-tech",
    name: "Georgia Institute of Technology",
    location: "Atlanta, GA",
    state: "GA",
    type: "public",
    earlyActionDeadline: "10-15",
    regularDecisionDeadline: "01-04",
    website: "https://admission.gatech.edu",
    acceptanceRate: 16.0,
  },
  {
    id: "harvey-mudd",
    name: "Harvey Mudd College",
    location: "Claremont, CA",
    state: "CA",
    type: "private",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "01-05",
    website: "https://www.hmc.edu/admission",
    acceptanceRate: 10.7,
  },
  {
    id: "rose-hulman",
    name: "Rose-Hulman Institute of Technology",
    location: "Terre Haute, IN",
    state: "IN",
    type: "private",
    regularDecisionDeadline: "02-01",
    website: "https://www.rose-hulman.edu/admissions",
    acceptanceRate: 57.0,
  },
  // Top Liberal Arts
  {
    id: "williams",
    name: "Williams College",
    location: "Williamstown, MA",
    state: "MA",
    type: "private",
    earlyDecisionDeadline: "11-15",
    regularDecisionDeadline: "01-08",
    website: "https://admission.williams.edu",
    acceptanceRate: 8.0,
  },
  {
    id: "amherst",
    name: "Amherst College",
    location: "Amherst, MA",
    state: "MA",
    type: "private",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "01-03",
    website: "https://www.amherst.edu/admission",
    acceptanceRate: 7.0,
  },
  {
    id: "swarthmore",
    name: "Swarthmore College",
    location: "Swarthmore, PA",
    state: "PA",
    type: "private",
    earlyDecisionDeadline: "11-15",
    regularDecisionDeadline: "01-03",
    website: "https://www.swarthmore.edu/admissions",
    acceptanceRate: 7.0,
  },
  {
    id: "wellesley",
    name: "Wellesley College",
    location: "Wellesley, MA",
    state: "MA",
    type: "private",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "01-08",
    website: "https://www.wellesley.edu/admission",
    acceptanceRate: 14.0,
  },
  {
    id: "pomona",
    name: "Pomona College",
    location: "Claremont, CA",
    state: "CA",
    type: "private",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "01-08",
    website: "https://www.pomona.edu/admissions",
    acceptanceRate: 7.0,
  },
  {
    id: "middlebury",
    name: "Middlebury College",
    location: "Middlebury, VT",
    state: "VT",
    type: "private",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "01-03",
    website: "https://www.middlebury.edu/admissions",
    acceptanceRate: 13.0,
  },
  {
    id: "bowdoin",
    name: "Bowdoin College",
    location: "Brunswick, ME",
    state: "ME",
    type: "private",
    earlyDecisionDeadline: "11-15",
    regularDecisionDeadline: "01-05",
    website: "https://www.bowdoin.edu/admissions",
    acceptanceRate: 8.9,
  },
  {
    id: "carleton",
    name: "Carleton College",
    location: "Northfield, MN",
    state: "MN",
    type: "private",
    earlyDecisionDeadline: "11-15",
    regularDecisionDeadline: "01-15",
    website: "https://www.carleton.edu/admissions",
    acceptanceRate: 17.0,
  },
  {
    id: "colby",
    name: "Colby College",
    location: "Waterville, ME",
    state: "ME",
    type: "private",
    earlyDecisionDeadline: "11-15",
    regularDecisionDeadline: "01-01",
    website: "https://www.colby.edu/admissions",
    acceptanceRate: 10.0,
  },
  {
    id: "hamilton",
    name: "Hamilton College",
    location: "Clinton, NY",
    state: "NY",
    type: "private",
    earlyDecisionDeadline: "11-15",
    regularDecisionDeadline: "01-01",
    website: "https://www.hamilton.edu/admission",
    acceptanceRate: 11.0,
  },
  {
    id: "vassar",
    name: "Vassar College",
    location: "Poughkeepsie, NY",
    state: "NY",
    type: "private",
    earlyDecisionDeadline: "11-15",
    regularDecisionDeadline: "01-01",
    website: "https://admissions.vassar.edu",
    acceptanceRate: 19.0,
  },
  {
    id: "colgate",
    name: "Colgate University",
    location: "Hamilton, NY",
    state: "NY",
    type: "private",
    earlyDecisionDeadline: "11-15",
    regularDecisionDeadline: "01-15",
    website: "https://www.colgate.edu/admission",
    acceptanceRate: 16.0,
  },
  {
    id: "bates",
    name: "Bates College",
    location: "Lewiston, ME",
    state: "ME",
    type: "private",
    earlyDecisionDeadline: "11-15",
    regularDecisionDeadline: "01-01",
    website: "https://www.bates.edu/admission",
    acceptanceRate: 12.0,
  },
  {
    id: "grinnell",
    name: "Grinnell College",
    location: "Grinnell, IA",
    state: "IA",
    type: "private",
    earlyDecisionDeadline: "11-15",
    regularDecisionDeadline: "01-15",
    website: "https://www.grinnell.edu/admission",
    acceptanceRate: 11.0,
  },
  {
    id: "davidson",
    name: "Davidson College",
    location: "Davidson, NC",
    state: "NC",
    type: "private",
    earlyDecisionDeadline: "11-15",
    regularDecisionDeadline: "01-15",
    website: "https://www.davidson.edu/admission",
    acceptanceRate: 15.0,
  },
  {
    id: "oberlin",
    name: "Oberlin College",
    location: "Oberlin, OH",
    state: "OH",
    type: "private",
    earlyDecisionDeadline: "11-15",
    regularDecisionDeadline: "01-15",
    website: "https://www.oberlin.edu/admissions",
    acceptanceRate: 27.0,
  },
  {
    id: "macalester",
    name: "Macalester College",
    location: "Saint Paul, MN",
    state: "MN",
    type: "private",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "01-15",
    website: "https://www.macalester.edu/admissions",
    acceptanceRate: 29.0,
  },
  {
    id: "haverford",
    name: "Haverford College",
    location: "Haverford, PA",
    state: "PA",
    type: "private",
    earlyDecisionDeadline: "11-15",
    regularDecisionDeadline: "01-15",
    website: "https://www.haverford.edu/admission",
    acceptanceRate: 10.0,
  },
  {
    id: "claremont-mckenna",
    name: "Claremont McKenna College",
    location: "Claremont, CA",
    state: "CA",
    type: "private",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "01-10",
    website: "https://www.cmc.edu/admission",
    acceptanceRate: 9.0,
  },
  {
    id: "smith",
    name: "Smith College",
    location: "Northampton, MA",
    state: "MA",
    type: "private",
    earlyDecisionDeadline: "11-15",
    regularDecisionDeadline: "01-15",
    website: "https://www.smith.edu/admission",
    acceptanceRate: 31.0,
  },
  {
    id: "mount-holyoke",
    name: "Mount Holyoke College",
    location: "South Hadley, MA",
    state: "MA",
    type: "private",
    earlyDecisionDeadline: "11-15",
    regularDecisionDeadline: "01-15",
    website: "https://www.mtholyoke.edu/admission",
    acceptanceRate: 30.0,
  },
  {
    id: "wesleyan",
    name: "Wesleyan University",
    location: "Middletown, CT",
    state: "CT",
    type: "private",
    earlyDecisionDeadline: "11-15",
    regularDecisionDeadline: "01-01",
    website: "https://www.wesleyan.edu/admission",
    acceptanceRate: 16.0,
  },
  {
    id: "trinity",
    name: "Trinity College",
    location: "Hartford, CT",
    state: "CT",
    type: "private",
    earlyDecisionDeadline: "11-15",
    regularDecisionDeadline: "01-15",
    website: "https://www.trincoll.edu/admissions",
    acceptanceRate: 28.0,
  },
  {
    id: "conn-college",
    name: "Connecticut College",
    location: "New London, CT",
    state: "CT",
    type: "private",
    earlyDecisionDeadline: "11-15",
    regularDecisionDeadline: "01-15",
    website: "https://www.conncoll.edu/admission",
    acceptanceRate: 34.0,
  },
  {
    id: "bryn-mawr",
    name: "Bryn Mawr College",
    location: "Bryn Mawr, PA",
    state: "PA",
    type: "private",
    earlyDecisionDeadline: "11-15",
    regularDecisionDeadline: "01-15",
    website: "https://www.brynmawr.edu/admissions",
    acceptanceRate: 28.0,
  },
  {
    id: "barnard",
    name: "Barnard College",
    location: "New York, NY",
    state: "NY",
    type: "private",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "01-01",
    website: "https://admissions.barnard.edu",
    acceptanceRate: 11.0,
  },
  // Top National Universities (Non-Ivy)
  {
    id: "duke",
    name: "Duke University",
    location: "Durham, NC",
    state: "NC",
    type: "private",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "01-02",
    website: "https://admissions.duke.edu",
    acceptanceRate: 6.0,
  },
  {
    id: "johns-hopkins",
    name: "Johns Hopkins University",
    location: "Baltimore, MD",
    state: "MD",
    type: "private",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "01-02",
    website: "https://apply.jhu.edu",
    acceptanceRate: 6.9,
  },
  {
    id: "northwestern",
    name: "Northwestern University",
    location: "Evanston, IL",
    state: "IL",
    type: "private",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "01-03",
    website: "https://undergradmission.northwestern.edu",
    acceptanceRate: 6.8,
  },
  {
    id: "vanderbilt",
    name: "Vanderbilt University",
    location: "Nashville, TN",
    state: "TN",
    type: "private",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "01-01",
    website: "https://admissions.vanderbilt.edu",
    acceptanceRate: 5.4,
  },
  {
    id: "rice",
    name: "Rice University",
    location: "Houston, TX",
    state: "TX",
    type: "private",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "01-04",
    website: "https://admissions.rice.edu",
    acceptanceRate: 8.7,
  },
  {
    id: "notre-dame",
    name: "University of Notre Dame",
    location: "Notre Dame, IN",
    state: "IN",
    type: "private",
    earlyActionDeadline: "11-01",
    regularDecisionDeadline: "01-01",
    website: "https://admissions.nd.edu",
    acceptanceRate: 12.0,
  },
  {
    id: "emory",
    name: "Emory University",
    location: "Atlanta, GA",
    state: "GA",
    type: "private",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "01-01",
    website: "https://apply.emory.edu",
    acceptanceRate: 11.0,
  },
  {
    id: "georgetown",
    name: "Georgetown University",
    location: "Washington, DC",
    state: "DC",
    type: "private",
    regularDecisionDeadline: "01-10",
    website: "https://uadmissions.georgetown.edu",
    acceptanceRate: 12.0,
  },
  {
    id: "tufts",
    name: "Tufts University",
    location: "Medford, MA",
    state: "MA",
    type: "private",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "01-04",
    website: "https://admissions.tufts.edu",
    acceptanceRate: 10.6,
  },
  {
    id: "washington-lee",
    name: "Washington and Lee University",
    location: "Lexington, VA",
    state: "VA",
    type: "private",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "01-01",
    website: "https://www.wlu.edu/admission",
    acceptanceRate: 18.0,
  },
  {
    id: "boston-college",
    name: "Boston College",
    location: "Chestnut Hill, MA",
    state: "MA",
    type: "private",
    earlyActionDeadline: "11-01",
    regularDecisionDeadline: "01-01",
    website: "https://www.bc.edu/content/bc-web/admission",
    acceptanceRate: 17.0,
  },
  {
    id: "bu",
    name: "Boston University",
    location: "Boston, MA",
    state: "MA",
    type: "private",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "01-04",
    website: "https://www.bu.edu/admissions",
    acceptanceRate: 14.0,
  },
  {
    id: "usc",
    name: "University of Southern California",
    location: "Los Angeles, CA",
    state: "CA",
    type: "private",
    earlyActionDeadline: "11-01",
    regularDecisionDeadline: "01-15",
    website: "https://admission.usc.edu",
    acceptanceRate: 9.0,
  },
  {
    id: "tulane",
    name: "Tulane University",
    location: "New Orleans, LA",
    state: "LA",
    type: "private",
    earlyActionDeadline: "11-15",
    regularDecisionDeadline: "01-15",
    website: "https://admission.tulane.edu",
    acceptanceRate: 13.0,
  },
  {
    id: "wake-forest",
    name: "Wake Forest University",
    location: "Winston-Salem, NC",
    state: "NC",
    type: "private",
    earlyDecisionDeadline: "11-15",
    regularDecisionDeadline: "01-01",
    website: "https://admissions.wfu.edu",
    acceptanceRate: 23.0,
  },
  {
    id: "lehigh",
    name: "Lehigh University",
    location: "Bethlehem, PA",
    state: "PA",
    type: "private",
    earlyDecisionDeadline: "11-15",
    regularDecisionDeadline: "01-15",
    website: "https://www1.lehigh.edu/admissions",
    acceptanceRate: 33.0,
  },
  {
    id: "case-western",
    name: "Case Western Reserve University",
    location: "Cleveland, OH",
    state: "OH",
    type: "private",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "01-15",
    website: "https://case.edu/admission",
    acceptanceRate: 27.0,
  },
  {
    id: "northeastern",
    name: "Northeastern University",
    location: "Boston, MA",
    state: "MA",
    type: "private",
    earlyActionDeadline: "11-01",
    regularDecisionDeadline: "01-01",
    website: "https://admissions.northeastern.edu",
    acceptanceRate: 7.0,
  },
  {
    id: "brandeis",
    name: "Brandeis University",
    location: "Waltham, MA",
    state: "MA",
    type: "private",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "01-01",
    website: "https://www.brandeis.edu/admissions",
    acceptanceRate: 26.0,
  },
  {
    id: "nyu",
    name: "New York University",
    location: "New York, NY",
    state: "NY",
    type: "private",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "01-05",
    website: "https://www.nyu.edu/admissions",
    acceptanceRate: 12.2,
  },
  {
    id: "george-washington",
    name: "George Washington University",
    location: "Washington, DC",
    state: "DC",
    type: "private",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "01-05",
    website: "https://undergraduate.admissions.gwu.edu",
    acceptanceRate: 40.0,
  },
  // Major Public Universities
  {
    id: "uc-berkeley",
    name: "University of California, Berkeley",
    location: "Berkeley, CA",
    state: "CA",
    type: "public",
    regularDecisionDeadline: "11-30",
    website: "https://admissions.berkeley.edu",
    acceptanceRate: 11.4,
  },
  {
    id: "ucla",
    name: "University of California, Los Angeles",
    location: "Los Angeles, CA",
    state: "CA",
    type: "public",
    regularDecisionDeadline: "11-30",
    website: "https://www.admission.ucla.edu",
    acceptanceRate: 8.8,
  },
  {
    id: "uc-san-diego",
    name: "University of California, San Diego",
    location: "La Jolla, CA",
    state: "CA",
    type: "public",
    regularDecisionDeadline: "11-30",
    website: "https://admissions.ucsd.edu",
    acceptanceRate: 24.0,
  },
  {
    id: "uc-santa-barbara",
    name: "University of California, Santa Barbara",
    location: "Santa Barbara, CA",
    state: "CA",
    type: "public",
    regularDecisionDeadline: "11-30",
    website: "https://www.admissions.ucsb.edu",
    acceptanceRate: 26.0,
  },
  {
    id: "uc-davis",
    name: "University of California, Davis",
    location: "Davis, CA",
    state: "CA",
    type: "public",
    regularDecisionDeadline: "11-30",
    website: "https://admissions.ucdavis.edu",
    acceptanceRate: 37.0,
  },
  {
    id: "uc-irvine",
    name: "University of California, Irvine",
    location: "Irvine, CA",
    state: "CA",
    type: "public",
    regularDecisionDeadline: "11-30",
    website: "https://admissions.uci.edu",
    acceptanceRate: 26.5,
  },
  {
    id: "uc-santa-cruz",
    name: "University of California, Santa Cruz",
    location: "Santa Cruz, CA",
    state: "CA",
    type: "public",
    regularDecisionDeadline: "11-30",
    website: "https://admissions.ucsc.edu",
    acceptanceRate: 47.0,
  },
  {
    id: "uc-riverside",
    name: "University of California, Riverside",
    location: "Riverside, CA",
    state: "CA",
    type: "public",
    regularDecisionDeadline: "11-30",
    website: "https://admissions.ucr.edu",
    acceptanceRate: 55.0,
  },
  {
    id: "umich",
    name: "University of Michigan",
    location: "Ann Arbor, MI",
    state: "MI",
    type: "public",
    earlyActionDeadline: "11-01",
    regularDecisionDeadline: "02-01",
    website: "https://admissions.umich.edu",
    acceptanceRate: 17.0,
  },
  {
    id: "unc",
    name: "University of North Carolina at Chapel Hill",
    location: "Chapel Hill, NC",
    state: "NC",
    type: "public",
    earlyActionDeadline: "10-15",
    regularDecisionDeadline: "01-15",
    website: "https://admissions.unc.edu",
    acceptanceRate: 17.0,
  },
  {
    id: "virginia",
    name: "University of Virginia",
    location: "Charlottesville, VA",
    state: "VA",
    type: "public",
    earlyActionDeadline: "11-01",
    regularDecisionDeadline: "01-05",
    website: "https://admission.virginia.edu",
    acceptanceRate: 17.0,
  },
  {
    id: "william-mary",
    name: "College of William & Mary",
    location: "Williamsburg, VA",
    state: "VA",
    type: "public",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "02-01",
    website: "https://www.wm.edu/admission",
    acceptanceRate: 33.0,
  },
  {
    id: "ut-austin",
    name: "University of Texas at Austin",
    location: "Austin, TX",
    state: "TX",
    type: "public",
    earlyActionDeadline: "11-01",
    regularDecisionDeadline: "12-01",
    website: "https://admissions.utexas.edu",
    acceptanceRate: 29.0,
  },
  {
    id: "florida",
    name: "University of Florida",
    location: "Gainesville, FL",
    state: "FL",
    type: "public",
    regularDecisionDeadline: "11-01",
    website: "https://admissions.ufl.edu",
    acceptanceRate: 23.0,
  },
  {
    id: "ohio-state",
    name: "Ohio State University",
    location: "Columbus, OH",
    state: "OH",
    type: "public",
    earlyActionDeadline: "11-01",
    regularDecisionDeadline: "02-01",
    website: "https://undergrad.osu.edu/apply",
    acceptanceRate: 53.0,
  },
  {
    id: "penn-state",
    name: "Pennsylvania State University",
    location: "University Park, PA",
    state: "PA",
    type: "public",
    regularDecisionDeadline: "11-30",
    website: "https://admissions.psu.edu",
    acceptanceRate: 54.0,
  },
  {
    id: "purdue",
    name: "Purdue University",
    location: "West Lafayette, IN",
    state: "IN",
    type: "public",
    earlyActionDeadline: "11-01",
    regularDecisionDeadline: "01-15",
    website: "https://www.admissions.purdue.edu",
    acceptanceRate: 53.0,
  },
  {
    id: "illinois",
    name: "University of Illinois Urbana-Champaign",
    location: "Champaign, IL",
    state: "IL",
    type: "public",
    earlyActionDeadline: "11-01",
    regularDecisionDeadline: "01-05",
    website: "https://admissions.illinois.edu",
    acceptanceRate: 44.0,
  },
  {
    id: "wisconsin",
    name: "University of Wisconsin-Madison",
    location: "Madison, WI",
    state: "WI",
    type: "public",
    earlyActionDeadline: "11-01",
    regularDecisionDeadline: "02-01",
    website: "https://admissions.wisc.edu",
    acceptanceRate: 49.0,
  },
  {
    id: "minnesota",
    name: "University of Minnesota Twin Cities",
    location: "Minneapolis, MN",
    state: "MN",
    type: "public",
    regularDecisionDeadline: "01-01",
    website: "https://admissions.tc.umn.edu",
    acceptanceRate: 57.0,
  },
  {
    id: "indiana",
    name: "Indiana University Bloomington",
    location: "Bloomington, IN",
    state: "IN",
    type: "public",
    earlyActionDeadline: "11-01",
    regularDecisionDeadline: "02-01",
    website: "https://admissions.indiana.edu",
    acceptanceRate: 67.0,
  },
  {
    id: "michigan-state",
    name: "Michigan State University",
    location: "East Lansing, MI",
    state: "MI",
    type: "public",
    regularDecisionDeadline: "11-01",
    website: "https://admissions.msu.edu",
    acceptanceRate: 76.0,
  },
  {
    id: "maryland",
    name: "University of Maryland, College Park",
    location: "College Park, MD",
    state: "MD",
    type: "public",
    earlyActionDeadline: "11-01",
    regularDecisionDeadline: "01-20",
    website: "https://admissions.umd.edu",
    acceptanceRate: 44.0,
  },
  {
    id: "pitt",
    name: "University of Pittsburgh",
    location: "Pittsburgh, PA",
    state: "PA",
    type: "public",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "01-15",
    website: "https://www.admissions.pitt.edu",
    acceptanceRate: 57.0,
  },
  {
    id: "rutgers",
    name: "Rutgers University-New Brunswick",
    location: "New Brunswick, NJ",
    state: "NJ",
    type: "public",
    regularDecisionDeadline: "12-01",
    website: "https://admissions.rutgers.edu",
    acceptanceRate: 66.0,
  },
  {
    id: "colorado",
    name: "University of Colorado Boulder",
    location: "Boulder, CO",
    state: "CO",
    type: "public",
    regularDecisionDeadline: "01-15",
    website: "https://www.colorado.edu/admissions",
    acceptanceRate: 80.0,
  },
  {
    id: "arizona",
    name: "University of Arizona",
    location: "Tucson, AZ",
    state: "AZ",
    type: "public",
    regularDecisionDeadline: "05-01",
    website: "https://admissions.arizona.edu",
    acceptanceRate: 85.0,
  },
  {
    id: "washington",
    name: "University of Washington",
    location: "Seattle, WA",
    state: "WA",
    type: "public",
    regularDecisionDeadline: "11-15",
    website: "https://admit.washington.edu",
    acceptanceRate: 48.0,
  },
  {
    id: "usc-columbia",
    name: "University of South Carolina",
    location: "Columbia, SC",
    state: "SC",
    type: "public",
    earlyActionDeadline: "10-15",
    regularDecisionDeadline: "12-01",
    website: "https://sc.edu/admissions",
    acceptanceRate: 64.0,
  },
  {
    id: "iowa",
    name: "University of Iowa",
    location: "Iowa City, IA",
    state: "IA",
    type: "public",
    regularDecisionDeadline: "05-01",
    website: "https://admissions.uiowa.edu",
    acceptanceRate: 82.0,
  },
  {
    id: "iowa-state",
    name: "Iowa State University",
    location: "Ames, IA",
    state: "IA",
    type: "public",
    regularDecisionDeadline: "07-01",
    website: "https://www.admissions.iastate.edu",
    acceptanceRate: 91.0,
  },
  {
    id: "missouri",
    name: "University of Missouri",
    location: "Columbia, MO",
    state: "MO",
    type: "public",
    regularDecisionDeadline: "05-01",
    website: "https://admissions.missouri.edu",
    acceptanceRate: 78.0,
  },
  {
    id: "kansas",
    name: "University of Kansas",
    location: "Lawrence, KS",
    state: "KS",
    type: "public",
    regularDecisionDeadline: "04-01",
    website: "https://admissions.ku.edu",
    acceptanceRate: 88.0,
  },
  {
    id: "nebraska",
    name: "University of Nebraska-Lincoln",
    location: "Lincoln, NE",
    state: "NE",
    type: "public",
    regularDecisionDeadline: "05-01",
    website: "https://admissions.unl.edu",
    acceptanceRate: 80.0,
  },
  {
    id: "tennessee",
    name: "University of Tennessee",
    location: "Knoxville, TN",
    state: "TN",
    type: "public",
    regularDecisionDeadline: "12-01",
    website: "https://admissions.utk.edu",
    acceptanceRate: 67.0,
  },
  {
    id: "alabama",
    name: "University of Alabama",
    location: "Tuscaloosa, AL",
    state: "AL",
    type: "public",
    regularDecisionDeadline: "06-01",
    website: "https://gobama.ua.edu",
    acceptanceRate: 80.0,
  },
  {
    id: "auburn",
    name: "Auburn University",
    location: "Auburn, AL",
    state: "AL",
    type: "public",
    regularDecisionDeadline: "02-01",
    website: "https://www.auburn.edu/admissions",
    acceptanceRate: 76.0,
  },
  {
    id: "clemson",
    name: "Clemson University",
    location: "Clemson, SC",
    state: "SC",
    type: "public",
    earlyActionDeadline: "11-01",
    regularDecisionDeadline: "05-01",
    website: "https://www.clemson.edu/admissions",
    acceptanceRate: 43.0,
  },
  {
    id: "virginia-tech",
    name: "Virginia Tech",
    location: "Blacksburg, VA",
    state: "VA",
    type: "public",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "01-15",
    website: "https://www.admissions.vt.edu",
    acceptanceRate: 57.0,
  },
  {
    id: "nc-state",
    name: "North Carolina State University",
    location: "Raleigh, NC",
    state: "NC",
    type: "public",
    earlyActionDeadline: "11-01",
    regularDecisionDeadline: "02-01",
    website: "https://admissions.ncsu.edu",
    acceptanceRate: 45.0,
  },
  {
    id: "fsu",
    name: "Florida State University",
    location: "Tallahassee, FL",
    state: "FL",
    type: "public",
    earlyActionDeadline: "11-15",
    regularDecisionDeadline: "03-01",
    website: "https://admissions.fsu.edu",
    acceptanceRate: 25.0,
  },
  {
    id: "miami-fl",
    name: "University of Miami",
    location: "Coral Gables, FL",
    state: "FL",
    type: "private",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "01-01",
    website: "https://www.miami.edu/admission",
    acceptanceRate: 19.0,
  },
  {
    id: "uconn",
    name: "University of Connecticut",
    location: "Storrs, CT",
    state: "CT",
    type: "public",
    earlyActionDeadline: "11-01",
    regularDecisionDeadline: "01-15",
    website: "https://admissions.uconn.edu",
    acceptanceRate: 56.0,
  },
  {
    id: "stony-brook",
    name: "Stony Brook University",
    location: "Stony Brook, NY",
    state: "NY",
    type: "public",
    regularDecisionDeadline: "01-15",
    website: "https://www.stonybrook.edu/admissions",
    acceptanceRate: 49.0,
  },
  {
    id: "buffalo",
    name: "University at Buffalo",
    location: "Buffalo, NY",
    state: "NY",
    type: "public",
    regularDecisionDeadline: "02-01",
    website: "https://admissions.buffalo.edu",
    acceptanceRate: 63.0,
  },
  {
    id: "colorado-state",
    name: "Colorado State University",
    location: "Fort Collins, CO",
    state: "CO",
    type: "public",
    regularDecisionDeadline: "02-01",
    website: "https://admissions.colostate.edu",
    acceptanceRate: 84.0,
  },
  {
    id: "oregon",
    name: "University of Oregon",
    location: "Eugene, OR",
    state: "OR",
    type: "public",
    regularDecisionDeadline: "01-15",
    website: "https://admissions.uoregon.edu",
    acceptanceRate: 83.0,
  },
  {
    id: "oregon-state",
    name: "Oregon State University",
    location: "Corvallis, OR",
    state: "OR",
    type: "public",
    regularDecisionDeadline: "09-01",
    website: "https://admissions.oregonstate.edu",
    acceptanceRate: 82.0,
  },
  {
    id: "washington-state",
    name: "Washington State University",
    location: "Pullman, WA",
    state: "WA",
    type: "public",
    regularDecisionDeadline: "01-31",
    website: "https://admission.wsu.edu",
    acceptanceRate: 75.0,
  },
  // Additional Notable Schools
  {
    id: "uchicago",
    name: "University of Chicago",
    location: "Chicago, IL",
    state: "IL",
    type: "private",
    earlyActionDeadline: "11-01",
    regularDecisionDeadline: "01-02",
    website: "https://collegeadmissions.uchicago.edu",
    acceptanceRate: 5.4,
  },
  {
    id: "wustl",
    name: "Washington University in St. Louis",
    location: "St. Louis, MO",
    state: "MO",
    type: "private",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "01-02",
    website: "https://admissions.wustl.edu",
    acceptanceRate: 11.0,
  },
  {
    id: "rochester",
    name: "University of Rochester",
    location: "Rochester, NY",
    state: "NY",
    type: "private",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "01-05",
    website: "https://enrollment.rochester.edu/admissions",
    acceptanceRate: 26.0,
  },
  {
    id: "rpi",
    name: "Rensselaer Polytechnic Institute",
    location: "Troy, NY",
    state: "NY",
    type: "private",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "01-15",
    website: "https://admissions.rpi.edu",
    acceptanceRate: 43.0,
  },
  {
    id: "wpi",
    name: "Worcester Polytechnic Institute",
    location: "Worcester, MA",
    state: "MA",
    type: "private",
    earlyActionDeadline: "11-01",
    regularDecisionDeadline: "02-01",
    website: "https://www.wpi.edu/admissions",
    acceptanceRate: 49.0,
  },
  {
    id: "bucknell",
    name: "Bucknell University",
    location: "Lewisburg, PA",
    state: "PA",
    type: "private",
    earlyDecisionDeadline: "11-15",
    regularDecisionDeadline: "01-15",
    website: "https://www.bucknell.edu/admissions",
    acceptanceRate: 36.0,
  },
  {
    id: "lafayette",
    name: "Lafayette College",
    location: "Easton, PA",
    state: "PA",
    type: "private",
    earlyDecisionDeadline: "11-15",
    regularDecisionDeadline: "01-15",
    website: "https://admissions.lafayette.edu",
    acceptanceRate: 34.0,
  },
  {
    id: "gettysburg",
    name: "Gettysburg College",
    location: "Gettysburg, PA",
    state: "PA",
    type: "private",
    earlyDecisionDeadline: "11-15",
    regularDecisionDeadline: "02-01",
    website: "https://www.gettysburg.edu/admissions",
    acceptanceRate: 36.0,
  },
  {
    id: "dickinson",
    name: "Dickinson College",
    location: "Carlisle, PA",
    state: "PA",
    type: "private",
    earlyDecisionDeadline: "11-15",
    regularDecisionDeadline: "02-01",
    website: "https://www.dickinson.edu/admissions",
    acceptanceRate: 42.0,
  },
  {
    id: "muhlenberg",
    name: "Muhlenberg College",
    location: "Allentown, PA",
    state: "PA",
    type: "private",
    earlyDecisionDeadline: "02-15",
    regularDecisionDeadline: "02-15",
    website: "https://www.muhlenberg.edu/main/admissions",
    acceptanceRate: 52.0,
  },
  {
    id: "denison",
    name: "Denison University",
    location: "Granville, OH",
    state: "OH",
    type: "private",
    earlyDecisionDeadline: "11-15",
    regularDecisionDeadline: "01-15",
    website: "https://admission.denison.edu",
    acceptanceRate: 28.0,
  },
  {
    id: "kenyon",
    name: "Kenyon College",
    location: "Gambier, OH",
    state: "OH",
    type: "private",
    earlyDecisionDeadline: "11-15",
    regularDecisionDeadline: "01-15",
    website: "https://www.kenyon.edu/admissions",
    acceptanceRate: 29.0,
  },
  {
    id: "wooster",
    name: "College of Wooster",
    location: "Wooster, OH",
    state: "OH",
    type: "private",
    earlyDecisionDeadline: "12-01",
    regularDecisionDeadline: "02-15",
    website: "https://www.wooster.edu/admissions",
    acceptanceRate: 50.0,
  },
  {
    id: "depauw",
    name: "DePauw University",
    location: "Greencastle, IN",
    state: "IN",
    type: "private",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "02-01",
    website: "https://www.depauw.edu/admission",
    acceptanceRate: 57.0,
  },
  {
    id: "furman",
    name: "Furman University",
    location: "Greenville, SC",
    state: "SC",
    type: "private",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "01-15",
    website: "https://www.furman.edu/academics/admission",
    acceptanceRate: 57.0,
  },
  {
    id: "rhodes",
    name: "Rhodes College",
    location: "Memphis, TN",
    state: "TN",
    type: "private",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "02-01",
    website: "https://www.rhodes.edu/admission",
    acceptanceRate: 37.0,
  },
  {
    id: "sewanee",
    name: "Sewanee: The University of the South",
    location: "Sewanee, TN",
    state: "TN",
    type: "private",
    earlyDecisionDeadline: "11-15",
    regularDecisionDeadline: "02-01",
    website: "https://admissions.sewanee.edu",
    acceptanceRate: 53.0,
  },
  {
    id: "centre",
    name: "Centre College",
    location: "Danville, KY",
    state: "KY",
    type: "private",
    earlyDecisionDeadline: "12-01",
    regularDecisionDeadline: "02-01",
    website: "https://www.centre.edu/admission",
    acceptanceRate: 66.0,
  },
  {
    id: "hendrix",
    name: "Hendrix College",
    location: "Conway, AR",
    state: "AR",
    type: "private",
    regularDecisionDeadline: "08-01",
    website: "https://www.hendrix.edu/admission",
    acceptanceRate: 66.0,
  },
  {
    id: "reed",
    name: "Reed College",
    location: "Portland, OR",
    state: "OR",
    type: "private",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "01-15",
    website: "https://www.reed.edu/admission",
    acceptanceRate: 32.0,
  },
  {
    id: "whitman",
    name: "Whitman College",
    location: "Walla Walla, WA",
    state: "WA",
    type: "private",
    earlyDecisionDeadline: "11-15",
    regularDecisionDeadline: "01-15",
    website: "https://www.whitman.edu/admission",
    acceptanceRate: 44.0,
  },
  {
    id: "colorado-college",
    name: "Colorado College",
    location: "Colorado Springs, CO",
    state: "CO",
    type: "private",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "01-15",
    website: "https://www.coloradocollege.edu/admission",
    acceptanceRate: 14.0,
  },
  {
    id: "skidmore",
    name: "Skidmore College",
    location: "Saratoga Springs, NY",
    state: "NY",
    type: "private",
    earlyDecisionDeadline: "11-15",
    regularDecisionDeadline: "01-15",
    website: "https://www.skidmore.edu/admissions",
    acceptanceRate: 30.0,
  },
  {
    id: "union",
    name: "Union College",
    location: "Schenectady, NY",
    state: "NY",
    type: "private",
    earlyDecisionDeadline: "11-15",
    regularDecisionDeadline: "01-15",
    website: "https://www.union.edu/admissions",
    acceptanceRate: 39.0,
  },
  {
    id: "hobart-william-smith",
    name: "Hobart and William Smith Colleges",
    location: "Geneva, NY",
    state: "NY",
    type: "private",
    earlyDecisionDeadline: "11-15",
    regularDecisionDeadline: "02-01",
    website: "https://www.hws.edu/admissions",
    acceptanceRate: 57.0,
  },
  {
    id: "elon",
    name: "Elon University",
    location: "Elon, NC",
    state: "NC",
    type: "private",
    earlyActionDeadline: "11-01",
    regularDecisionDeadline: "01-10",
    website: "https://www.elon.edu/u/admissions",
    acceptanceRate: 71.0,
  },
  {
    id: "high-point",
    name: "High Point University",
    location: "High Point, NC",
    state: "NC",
    type: "private",
    regularDecisionDeadline: "03-01",
    website: "https://www.highpoint.edu/admissions",
    acceptanceRate: 70.0,
  },
  {
    id: "american",
    name: "American University",
    location: "Washington, DC",
    state: "DC",
    type: "private",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "01-15",
    website: "https://www.american.edu/admissions",
    acceptanceRate: 34.0,
  },
  {
    id: "fordham",
    name: "Fordham University",
    location: "New York, NY",
    state: "NY",
    type: "private",
    earlyActionDeadline: "11-01",
    regularDecisionDeadline: "01-01",
    website: "https://www.fordham.edu/admission",
    acceptanceRate: 46.0,
  },
  {
    id: "smu",
    name: "Southern Methodist University",
    location: "Dallas, TX",
    state: "TX",
    type: "private",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "01-15",
    website: "https://www.smu.edu/Enrollment/Admission",
    acceptanceRate: 52.0,
  },
  {
    id: "tcm",
    name: "Texas Christian University",
    location: "Fort Worth, TX",
    state: "TX",
    type: "private",
    earlyActionDeadline: "11-01",
    regularDecisionDeadline: "02-15",
    website: "https://admissions.tcu.edu",
    acceptanceRate: 42.0,
  },
  {
    id: "baylor",
    name: "Baylor University",
    location: "Waco, TX",
    state: "TX",
    type: "private",
    earlyActionDeadline: "11-01",
    regularDecisionDeadline: "02-01",
    website: "https://www.baylor.edu/admissions",
    acceptanceRate: 45.0,
  },
  {
    id: "gonzaga",
    name: "Gonzaga University",
    location: "Spokane, WA",
    state: "WA",
    type: "private",
    earlyActionDeadline: "11-15",
    regularDecisionDeadline: "02-01",
    website: "https://www.gonzaga.edu/undergraduate-admission",
    acceptanceRate: 65.0,
  },
  {
    id: "santa-clara",
    name: "Santa Clara University",
    location: "Santa Clara, CA",
    state: "CA",
    type: "private",
    earlyActionDeadline: "11-01",
    regularDecisionDeadline: "01-07",
    website: "https://www.scu.edu/admission",
    acceptanceRate: 51.0,
  },
  {
    id: "loyola-md",
    name: "Loyola University Maryland",
    location: "Baltimore, MD",
    state: "MD",
    type: "private",
    earlyActionDeadline: "11-15",
    regularDecisionDeadline: "01-15",
    website: "https://www.loyola.edu/admission",
    acceptanceRate: 73.0,
  },
  {
    id: "villanova",
    name: "Villanova University",
    location: "Villanova, PA",
    state: "PA",
    type: "private",
    earlyActionDeadline: "11-01",
    regularDecisionDeadline: "01-15",
    website: "https://www1.villanova.edu/university/undergraduate-admission.html",
    acceptanceRate: 24.0,
  },
  {
    id: "providence",
    name: "Providence College",
    location: "Providence, RI",
    state: "RI",
    type: "private",
    earlyActionDeadline: "11-01",
    regularDecisionDeadline: "01-15",
    website: "https://admission.providence.edu",
    acceptanceRate: 49.0,
  },
  {
    id: "holy-cross",
    name: "College of the Holy Cross",
    location: "Worcester, MA",
    state: "MA",
    type: "private",
    earlyDecisionDeadline: "11-15",
    regularDecisionDeadline: "01-15",
    website: "https://www.holycross.edu/admission",
    acceptanceRate: 28.0,
  },
  {
    id: "stlawrence",
    name: "St. Lawrence University",
    location: "Canton, NY",
    state: "NY",
    type: "private",
    earlyDecisionDeadline: "11-15",
    regularDecisionDeadline: "02-01",
    website: "https://www.stlawu.edu/admissions",
    acceptanceRate: 46.0,
  },
  {
    id: "ithaca",
    name: "Ithaca College",
    location: "Ithaca, NY",
    state: "NY",
    type: "private",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "02-01",
    website: "https://www.ithaca.edu/admission",
    acceptanceRate: 67.0,
  },
  {
    id: "drexel",
    name: "Drexel University",
    location: "Philadelphia, PA",
    state: "PA",
    type: "private",
    earlyActionDeadline: "11-01",
    regularDecisionDeadline: "03-01",
    website: "https://drexel.edu/undergrad-admissions",
    acceptanceRate: 76.0,
  },
  {
    id: "stevens",
    name: "Stevens Institute of Technology",
    location: "Hoboken, NJ",
    state: "NJ",
    type: "private",
    earlyDecisionDeadline: "11-15",
    regularDecisionDeadline: "02-01",
    website: "https://www.stevens.edu/admissions",
    acceptanceRate: 38.0,
  },
  {
    id: "kettering",
    name: "Kettering University",
    location: "Flint, MI",
    state: "MI",
    type: "private",
    regularDecisionDeadline: "07-01",
    website: "https://www.kettering.edu/admissions",
    acceptanceRate: 63.0,
  },
  {
    id: "suny-geneseo",
    name: "SUNY Geneseo",
    location: "Geneseo, NY",
    state: "NY",
    type: "public",
    regularDecisionDeadline: "01-01",
    website: "https://www.geneseo.edu/admissions",
    acceptanceRate: 55.0,
  },
  {
    id: "miami-oh",
    name: "Miami University",
    location: "Oxford, OH",
    state: "OH",
    type: "public",
    earlyDecisionDeadline: "11-01",
    regularDecisionDeadline: "02-01",
    website: "https://miamioh.edu/admission",
    acceptanceRate: 71.0,
  },
];

export function searchSchools(query: string): School[] {
  if (!query || query.trim().length === 0) return SCHOOLS;
  const q = query.toLowerCase().trim();
  return SCHOOLS.filter(
    (s) =>
      s.name.toLowerCase().includes(q) ||
      s.location.toLowerCase().includes(q) ||
      s.state.toLowerCase().includes(q)
  );
}

export function getSchoolById(id: string): School | undefined {
  return SCHOOLS.find((s) => s.id === id);
}